uid: 32a0758b-0424-4050-97b0-a524ba365912
info:
  name: Multi-Language Settings
  type: http
  seq: 4
http:
  method: PATCH
  url: '{{BASE_URL}}/api/v2/workspaces/6/email_templates/settings'
  body:
    type: json
    data: "{\n\t\"multi_locale\": true, // Boolean value\n\t\"locales\": [\"en_us\", \"fr_fr\"] // Only send when multi_locale is set to true.\n}"
