uid: 842ada7e-326f-464c-bc37-bcc96a36812a
info:
  name: Update default config
  type: http
  seq: 2
http:
  method: PATCH
  url: '{{BASE_URL}}/api/v3/table_configs/:id'
  headers:
  - name: X-Group-Key
    value: '{{GroupKey}}'
  body:
    type: json
    data: |-
      {
          "config": {
              "columns": [
                  {
                      "name": "Invoice Number",
                      "accessor": "invoice_number",
                      "columnHeaderAlign": "left",
                      "enableSort": true,
                      "enableSearch": true,
                      "enableFilter": true,
                      "enableSkeleton": true,
                      "secondarySort": "due_date",
                      "rowDataAlign": "right",
                      "rowDataType": "string",
                      "filterType": "text",
                      "skeletonWidthInPX": 100,
                      "skeletonHeightInPX": 20,
                      "filterComparator": "equals"
                  },
                  {
                      "name": "Customer Name",
                      "accessor": "customer_name",
                      "columnHeaderAlign": "center",
                      "enableSort": true,
                      "enableSearch": true,
                      "enableFilter": true,
                      "enableSkeleton": true,
                      "secondarySort": "invoice_number",
                      "rowDataAlign": "left",
                      "rowDataType": "string",
                      "filterType": "text",
                      "skeletonWidthInPX": 120,
                      "skeletonHeightInPX": 20,
                      "filterComparator": "contains"
                  }
              ]
          }
      }
  auth:
    type: bearer
    token: '{{BearerToken}}'
