uid: 9f848bcd-1263-4e5e-ba1d-660de9b256bf
info:
  name: Tenant Config
  type: http
  seq: 55
http:
  method: GET
  url: '{{BASE_URL}}/api/v3/tenant_configs'
  headers:
  - name: accept
    value: text/plain
  - name: accept-language
    value: en-GB,en-US;q=0.9,en;q=0.8
  - name: app-code
    value: sage_network
  - name: applicationname
    value: Sage Connect UI
  - name: authorization
    value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InpRTEFFQjdGRkFIcmlRNFFoMTJRSyJ9.eyJodHRwczovL3NhZ2UuY29tL3NjaS9pZHAiOiJDbG91ZElEIiwiaXNzIjoiaHR0cHM6Ly9pZC1zaGFkb3cuc2FnZS5jb20vIiwic3ViIjoiYXV0aDB8MGEyNjgyNzBkZDdlYzNmMGJlZDQxM2FiYThjNWQ4ZjVmODc5M2NmMDhiNGYwM2RkIiwiYXVkIjpbInNuZXQtZGV2L25ldHdvcmsvYXBpIiwiaHR0cHM6Ly9zYWdlLWNpZC1zaGFkb3cuc2FnZWlkbm9ucHJvZC5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzcyMjc1MTc5LCJleHAiOjE3NzIzMDM5NzksInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiJmN1Jua084VmFIWmFwcWJqRjVOaWRjSTg4MGM5SXZ1QyJ9.wBTEfG1oqdzPmnaRk_j90ba9xdIkJ79nIecJiJMu7crCMQPL1v_ssFCrUBVCwZlYCZRvKD_ZJk3VT4zyzMWKeWJ1Hbsm9k2Tid2DUYUF5rjHVExG_HmLPjvpAAGI8USMgvfeMMidk57wKTCkc6ftCxBm4efpqk4lPSF1oGLVHGIrX9GFLUX8MHIpbu0zD_JYdWY_2CbQgbaCSYXdd0VbNVBohDUgRoXTelo4YKSCT8FqDPbgbFIKCXGqQF_qukgkwVZhsRZEGONvjV9cSbPW-Mqw5vIneARQbwytlPz2uQBffoiciBqBJqxFn94yeHg8JrnVo6G94SyoYY8yWW772A
  - name: cache-control
    value: no-cache
  - name: Cookie
    value: optimizelyEndUserId=oeu1714212545477r0.7006622017031621; _ga=GA1.1.1886583999.1713171292; _tt_enable_cookie=1; _ttp=AJqZADNiHXBY_TWTMsOX23jiWZ0.tt.1; _cs_c=0; ELOQUA=GUID=6FA05DC0592C41A6A8ECCB12BC3BC8EF; IR_PI=e2eb6f41-5102-11f0-bc6c-8336a5531e15%7C1750773328087; ajs_anonymous_id=2385df91-b68b-463b-aba5-73086984ffe6; fs_uid=#G2QXT#fce03d22-e5a4-40b9-81fe-bcae1a948022:1bdc3949-dddc-4895-bb7c-95b50c595d2a:1760113066075::2#77554506#/1791630975; nmstat=df4d4a14-07ca-8537-57e7-9a4e8a913fe6; optimizelySession=0; _gcl_au=1.1.2113074849.1771876058; _cs_id=9046d562-0fc2-ab2c-f0f9-4697ad5c8673.1750764586.5.1771876067.1771876067.1764010677.1784928586355.1.x; IR_gbd=sage.com; IR_29089=1771876067152%7C0%7C1771876067152%7C%7C; _fbp=fb.1.1771876072768.883532966848964477; _cfuvid=WLD6yylt1Fq1N7DMdQhPi2gy7pkDKCGOxoqGMpKcGAs-1772104709115-0.0.1.1-604800000; utag_main=v_id:018f2ef08c150017dc20d72cdf4f05075005e06d00942$dc_visit:15$_sn:9$_se:12%3Bexp-session$_ss:0%3Bexp-session$_st:1772106520028%3Bexp-session$ses_id:1772104707123%3Bexp-session$_pn:2%3Bexp-session$dc_event:2%3Bexp-session$dc_region:eu-west-1%3Bexp-session; _ga_PE4Z9JJWVN=GS2.1.s1772104709$o26$g1$t1772104720$j49$l0$h0; _rdt_uuid=1771876068641.6df64b96-68bb-43cc-8dd0-3bbc96280ae2; __cf_bm=.qvw_lvjfKJ3fKS399bT26Eo6d9lK04gr7vG6ovjSiU-1772275144-1.0.1.1-aIUKRkp_ca4BSpQ42DcjXwzjgtGoA5XancxvgTdfeyNPDWQnRLIDLXHdzlZsMxy1.LkxpuAFQ6i8P3.hCEzPfD29ekLhDubrqEO5uk9R90M; _legacy_auth0.f7RnkO8VaHZapqbjF5NidcI880c9IvuC.is.authenticated=true; auth0.f7RnkO8VaHZapqbjF5NidcI880c9IvuC.is.authenticated=true; _cfuvid=lIbta9zmjRxTZIS0BsIIRJuDhKgfgThjEwrIcPUvgU8-1772275187255-0.0.1.1-604800000
  - name: expires
    value: '-1'
  - name: group-key
    value: 8bd0f433-faca-a1ce-d04d-b80c0c73d44e
  - name: newrelic
    value: eyJ2IjpbMCwxXSwiZCI6eyJ0eSI6IkJyb3dzZXIiLCJhYyI6IjYyMjAyNDMiLCJhcCI6IjU5NDU3Mzg3NCIsImlkIjoiMjUwMDEzNWZhNTNmZjI0NiIsInRyIjoiYjRjMzYzZGE4OTJjOTc2ZTFiNDFjN2VjYWE4ZTM1ZDEiLCJ0aSI6MTc3MjI3NTE5MTIyNCwidGsiOiIzMDQ1NTcwIn19
  - name: pragma
    value: no-cache
  - name: priority
    value: u=1, i
  - name: referer
    value: https://qa.network-eng.sage.com/?code=pjPE1xiQBbiv5vAZ3ax57YyQbP84e3PrRiRtddGr2QCJi&state=dm9NcExWTzJUdjJ0eTZQeGw4SnZpSURoR24zQkJLU0hvRVBsY0pXVkdMYw%3D%3D
  - name: sec-ch-ua
    value: '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"'
  - name: sec-ch-ua-mobile
    value: ?0
  - name: sec-ch-ua-platform
    value: '"macOS"'
  - name: sec-fetch-dest
    value: empty
  - name: sec-fetch-mode
    value: cors
  - name: sec-fetch-site
    value: same-origin
  - name: traceparent
    value: 00-b4c363da892c976e1b41c7ecaa8e35d1-2500135fa53ff246-01
  - name: tracestate
    value: 3045570@nr=0-1-6220243-594573874-2500135fa53ff246----1772275191224
  - name: user-agent
    value: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36
  - name: x-group-key
    value: 8bd0f433-faca-a1ce-d04d-b80c0c73d44e
  - name: x-requested-with
    value: XMLHttpRequest
  - name: x-sxp-authorization
    value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InpRTEFFQjdGRkFIcmlRNFFoMTJRSyJ9.eyJodHRwczovL3NhZ2UuY29tL3NjaS9pZHAiOiJDbG91ZElEIiwiaXNzIjoiaHR0cHM6Ly9pZC1zaGFkb3cuc2FnZS5jb20vIiwic3ViIjoiYXV0aDB8MGEyNjgyNzBkZDdlYzNmMGJlZDQxM2FiYThjNWQ4ZjVmODc5M2NmMDhiNGYwM2RkIiwiYXVkIjpbIlNCQ0RTL2dsb2JhbCIsImh0dHBzOi8vc2FnZS1jaWQtc2hhZG93LnNhZ2VpZG5vbnByb2QuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTc3MjI3NTE5MCwiZXhwIjoxNzcyMzAzOTkwLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIHVzZXI6ZnVsbCIsImF6cCI6ImY3Um5rTzhWYUhaYXBxYmpGNU5pZGNJODgwYzlJdnVDIn0.t-wbUguGvj_bVLit1nnSVNIwjrWuFQg_-JBEYeJYGnlKxOckJBRJUqJxg9WPPHqNo7jnQMWjD6I7-FDXDZo2ttm5tthCa4ZcyNMjMbko5e_8cd_Vfb2QPKAqhs_4PS5JqD2Tdv0YCp5wriwRI4WRNQlud1pvw6yyT6NVlDK9gzs0W0Cu0ighLJGsAxZhThHxmNSa05fMPvdm9vKKdZ68vAzb2MvDVRbT0TuT5ZoqZHkxfUdK5_e8cCs6b3p_5Ztvbc6YHX82wNIX1zD4KRVlskFpTnRm9R1VpFOBA1iTXoDDZaLrKCBxv3vlP9LsLr9Za8SiuBs5MG_iX_6uWlApLw
