uid: 7208c53c-844c-4a91-9893-83280251ace9
info:
  name: Create Role
  type: http
  seq: 2
http:
  method: POST
  url: '{{BASE_URL}}/api/v3/contacts/roles'
  body:
    type: json
    data: |-
      {
          "label": "Account "
      }
  auth:
    type: bearer
    token: '{{BearerToken}}'
