uid: a69665b0-6c69-4902-ae91-270c52184b57
info:
  name: Index Roles
  type: http
  seq: 1
http:
  method: GET
  url: '{{BASE_URL}}/api/v3/contacts/roles'
  auth:
    type: bearer
    token: '{{BearerToken}}'
