uid: 32feabbe-0f31-4e0a-a9be-b99bc4fa4d03
info:
  name: Meta
  type: http
  seq: 1
http:
  method: GET
  url: '{{BASE_URL}}/api/v3/automated_messages/meta'
  auth:
    type: bearer
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJVUXlRME0wTWtOQk5rUkJOVGxETXpaQ056VXhPVVUyUkRZNU5EbEJOVVF6T0VSQk1EQXdNQSJ9.eyJpc3MiOiJodHRwczovL2lkLXNoYWRvdy5zYWdlLmNvbS8iLCJzdWIiOiJhdXRoMHxkMTkyNzZmYjRhMjc0YjYwYzZmOGMyODRjNzkwOTExZTE1ZjFmMGY2NmZhZTQ2YmMiLCJhdWQiOlsic25ldC1kZXYvbmV0d29yay9hcGkiLCJodHRwczovL3NhZ2UtY2lkLXNoYWRvdy5zYWdlaWRub25wcm9kLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MTcwNjI3NTMsImV4cCI6MTcxNzA5MTU1Mywic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImF6cCI6ImJDZ2dCNFZuTnloY1VtblRycDhpZUhqVHh3MzFXTHFZIn0.ChzumCeX_l-N9_OkG2TgsyqgtMbmJnKR9qVhNaDpJHT5nVFxSompgLzm_htBcy2nZOkrC8u1lw4VW7y0ZypmIKKG1478Gw8mBX1cCwRIOIqSL7mBZoFnRl-tIm-TEieGvxSKrHD7-vJBz5MHkrbQQbMFtWDdBuwsYM8NCdvraHM_-ifPbahQSWTR8HUWy1PEUqp6prkITcsORbDAVKR4W7DCcB1bj8I9QN3cLLjS1Fky9lqbm0te0-cptMnKFJeMUr4a_WKmbe01WnU8wcj2RBS6j9C1bDfqVw3mIrrbI_GNLpGjBc2MLt4Z-MEl0mcfkc0Rzdb37o0OICytd0GvLw
