uid: 88a1bec1-d361-481a-a81e-65c822e54f29
info:
  name: Create/Update Config - Inbox
  type: http
  seq: 3
http:
  method: POST
  url: '{{BASE_URL}}/api/v3/payment_providers'
  headers:
  - name: X-Group-Key
    value: '{{GroupKey}}'
  body:
    type: json
    data: |-
      {
          "servicer_account_id": "de0c1866-e9c6-4eb0-a675-7611bfdbfea1",
          "servicer_id": "7537d358-25a0-4d3f-8cbf-6c8a06acbee9",
          "min_amount": 10000000000000000000
      }
  auth:
    type: bearer
    token: '{{BearerToken}}'
