uid: 5f25a14a-0427-4f67-8795-62ecd0d73c67
info:
  name: Multi-Language Settings
  type: http
  seq: 4
http:
  method: PATCH
  url: '{{BASE_URL}}/api/v2/workspaces/6/email_templates/settings'
  body:
    type: json
    data: "{\n\t\"multi_locale\": true, // Boolean value\n\t\"locales\": [\"en_us\", \"fr_fr\"] // Only send when multi_locale is set to true.\n}"
